"""empty message

Revision ID: 09f494d89992
Revises: 
Create Date: 2020-03-11 02:30:51.301668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f494d89992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ImageStore',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('shortenedURL', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('visitsCount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('passwordOpted', sa.Boolean(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ImageStore')
    # ### end Alembic commands ###
